name: Build and Upload

on:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build for Linux
        run: ./gradlew packageReleaseAppImage --info

      - name: Archive Linux artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-artifacts
          path: build/compose/binaries/main-release/app/file-deleter/

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Build for Windows
        run: ./gradlew packageReleaseExe --info --build-cache

      - name: Archive Windows artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifacts
          path: build/compose/binaries/main-release/app/file-deleter/
